import styles from "./home.module.css";

import React from "react";

import Navbar from "../../components/Navbar";

const Home = () => {
  return (
    <div className={`container-fluid ${styles.home}`}>
      <Navbar />
      {/* fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk
      fgffhhahhahdjhdfksfghfhgkjhfgkshkjfghfsghkshgkjshkjgshgsjghfjksghjkshgkhfgjshjgfjfghkjshgjkhfghskjdfghkjshfgshkgjfghksfhgjk */}
    </div>
  );
};

export default Home;
